.KS
.\" start of Experiance
.sec
Extracurricular Activities

.ssec "Sprint Canoe Athlete" ""
.desc "May 2005 - Present"
.RS
.bul
Previous member of the Canadian Junior National Team (2015)
.bul
Previous member of the Senior National Development Team (2016)
.bul
National Champion in Junior men's C1 200m event (2018)
.bul
National Champion in Junior men's C2 200m, 500m, & 100m event (2017 - 2018)
.bul
National Medalist in Senior men's C2 200m & 500m (2019)
.RE
.KE
