.\" start of Projects
.sec
Projects
.reg
.br .\"line break

.ssec "Run-length encoding (C)" ""
.br
.small
Utilizes RLE encoding to encrypt and decrepit a given file

.ssec "StrokeMonitor (C++)"
.br
.small
Using an arduino this monitors the users strokerate, speed, and distance traveled in a canoe or kayak

.ssec "Filesystem-Emu (Java)"
.br .\" line break
.small
FAT based file system simulated using in Java
