.\" start of Projects
.sec
Projects
.reg
.br .\"line break
.ps 12 .\" set font size

.B "Run-length encoding (C)"
.br
.SM
.I "Utilizes RLE encoding to encrypt and decrepit a given file"

.reg
.B "StrokeMonitor (C++)"
.br
.SM
.I "Using an arduino this monitors the users strokerate, speed, and distance traveled in a canoe or kayak"

.reg
.B "Filesystem-Emu (Java)"
.br .\" line break
.SM
.I "FAT based file system simulated using in Java"
.sp -.10
